services:
  - type: web
    name: cargaison
    runtime: php
    buildCommand: |
      composer install
      npm install
      npm run build
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: PHP_VERSION
        value: "8.1"
      - key: NODE_VERSION
        value: "18.x"
    buildFilter:
      paths:
        - public/**
        - src/**
        - composer.json
        - composer.lock
        - package.json
        - tsconfig.json