services:
  - type: web
    name: cargaison
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: PHP_VERSION
        value: "8.1"
    buildFilter:
      paths:
        - public/**
        - src/**
        - composer.json
        - composer.lock